### ISSUE TITLE
Setup Travis CI

### ISSUE THREAD

**Issue by oliverbarnes** [BlueRidgeLabs/kimball#1]

**Comment by marcoow** [comment]
I'd copy this rule set: https://github.com/simplabs/rails_api_auth/blob/master/.rubocop.yml

**Comment by oliverbarnes** [comment]
will do. but this would be for #2 - going to tackle it now

**Comment by marcoow** [comment]
argh, sure

**Comment by oliverbarnes** [comment]
Assigned to Bill so he can create the account there

**Comment by cromulus** [comment]
Account setup.

**Comment by oliverbarnes** [comment]
thanks. would you send us the link and access info over email?

**Comment by cromulus** [comment]
Sure thing.

**Comment by oliverbarnes** [comment]
I think I already have full access, all settings seem editable. But it looks like it's all configured and the suite passes, I don't need to do anything else :) thanks, closing this issue
