### ISSUE TITLE
dotenv removal

### ISSUE THREAD

**Issue by oliverbarnes** [BlueRidgeLabs/kimball#10]
I see the commit removing it and mentioning a `local.yml` for the environment vars, how is that setup?

**Comment by marcoow** [comment]
I guess that would be answered by @cromulus ?

**Comment by cromulus** [comment]
Essentially, instead of assigning env variables in .env, local.yml contains
all relevant environment variables and should be used instead.

**Comment by marcoow** [comment]
@cromulus: where is that `local.yml` file ever read? Is that sth. new in Rails we're not aware of. `.env` is also useful on production to keep all the app config and secrets there on the server.

**Comment by cromulus** [comment]
@marcoow it is read here:
https://github.com/BlueRidgeLabs/kimball/blob/development/config/application.rb#L35

Yes, I prefer dot-env, but this is part of the smartchicago deploy as well:
https://github.com/BlueRidgeLabs/kimball/blob/development/config/deploy.rb#L46

**Comment by marcoow** [comment]
ah, didn't get that 👍🏻
