### ISSUE TITLE
Intermittent search test failure

### ISSUE THREAD

**Issue by oliverbarnes** [BlueRidgeLabs/kimball#14]
[this search controller test](https://github.com/BlueRidgeLabs/kimball/blob/development/test/controllers/search_controller_test.rb#L5) is giving grief by intermittently breaking both locally and on travis.

[this post](https://devmynd.com/blog/2014-2-dealing-with-failing-elasticserach-tests/) points to a possible solution which is a little involved. 

I'm disabling the test for now, this can be worked on the second milestone.

**Comment by oliverbarnes** [comment]
now [this people controller test](https://github.com/BlueRidgeLabs/kimball/blob/development/test/controllers/people_controller_test.rb#L74) and [this one as well](https://github.com/BlueRidgeLabs/kimball/blob/development/test/controllers/people_controller_test.rb#L90) are both failing due to a weird elastic search indexing issue, that might be related to [this tire issue](https://github.com/karmi/retire/issues/481). Tried to restart elasticsearch and clear its index, didn't help.

Given `tire` is retired and isn't supposed to run on rubies > 1.9, I'm also leaving this test as pending for the second milestone.

**Comment by oliverbarnes** [comment]
please ignore this last comment, was an environment variable issue. I'm using `dotenv` for now til #10 is cleared up, but keep having to stash it to commit stuff, so it wasn't loaded when running these last tests.

**Comment by marcoow** [comment]
I'd say ElasticSearch should be stubbed in the tests anyway - there will probably always be timing issues where the tests expects sth. to be already indexed that hasn't yet.

**Comment by oliverbarnes** [comment]
Agreed... Feels like stubbing a database though, and given ES is widely used I'd guess there are some proven strategies for testing it without needing to do that? In any case, once we get to it at the next milestone we can look into the possibilities. Migrating to a more up-to-date gem might help with this too, with fresher community content about it

**Comment by cromulus** [comment]
We should wait on this until #7 is resolved and/or smart chicago updates ES.

**Comment by cromulus** [comment]
Fixed several of the issues. Had to do with the delay in the generation of indexes. If you touch the person record, the index is added for that record.
