### ISSUE TITLE
Data modeling spike for scheduling

### ISSUE THREAD

**Issue by oliverbarnes** [BlueRidgeLabs/kimball#23]

**Comment by oliverbarnes** [comment]
So, this is what we came up with, in pseudo code: 

```
class Event < AR
  belongs_to :user
  has_many   :events
  has_many   :time_slots

  length  #=> in minutes, minimum to be defined.
  start   #=> datetime
  end     #=> datetime
end

class TimeSlot < AR
  belongs_to :user
  belongs_to :event

  start   #=> datetime
  end     #=> datetime
end

class Reservation < AR
  belongs_to :person
  belongs_to :user
  belongs_to :event, unique: { start/end overlap }

  start   #=> datetime
  end     #=> datetime
end
```

Nothing fancy, keeping it real simple for now. No state machine yet, reservations either being existant or not.

Looking ahead, we discussed a little of what the group invitation/scheduling could look like, and came to the conclusion that there could be many permutations, and really depends on the user story scenarios we want to contemplate. It would be useful to discuss it a bit upfront (before the next milestone) with @asyp, independently of implementation details.

**Comment by cromulus** [comment]
suggestion: potentially a buffer time in between calls? 
meaning, the event would also specify how much time in between calls we would want to keep? 
default to 0

**Comment by marcoow** [comment]
Also I don't think we actually need the `start` and `end` attributes on the event itself as those would be the same as the ones in the `Timeslot` anyway - as long as there's only one time slot assigned to the event. In the case of multiple time slots, start and end date on the event itself wouldn't make much sense anyway.

**Comment by oliverbarnes** [comment]
Good points. And the reservation start/end times are what really matter

**Comment by oliverbarnes** [comment]
@cromulus makes sense about the buffer, from experience. While mentoring at a bootcamp I'd open time windows students would fill up completely, leaving no breaks in between. It could get intense after a couple of sessions

**Comment by oliverbarnes** [comment]
@marcoow  discussed group invitations with Alexis and Bill over skype - consensus was to keep it dead simple, just adding more email fields for more invitees. Alexis will limit time slots so there's less room for non-matching reservations. 

Also, in the summer there will be multiple focus groups happening during a given period, providing more time slots to choose from, making this less of an issue

**Comment by marcoow** [comment]
see my comments here: https://github.com/BlueRidgeLabs/kimball/issues/24#issuecomment-179708400

I think we can really build a much simpler solution when @asyp will predefine the available time slots anyway.

**Comment by oliverbarnes** [comment]
Agreed, will implement it that way then
