### ISSUE TITLE
Scheduling phone calls with one person

### ISSUE THREAD

**Issue by oliverbarnes** [BlueRidgeLabs/kimball#24]
As an admin user 
I need to invite a person to a phone call
At a time fitting with my schedule
So I can interview her

As a person (research subject)
I want to respond to invitations to phone calls
Selecting a convenient time slot
So I can participate in a research session

**Scenarios**

Admin user selects time slots available to her
Defines the length of the call
Optionally defines a buffer time to ensure breaks between interviews
Writes up a description of the interview and what they're looking for
Sends out the invitation
Receives a notification the invite was sent, for future reference

Person receives an email invitation
Clicks on a link to select her time slot
Selects a time slot
Confirms the reservation
Admin receives a notification the reservation was made

**Constraints**

* No double booking
* Person should be uniquely identified (by a temporary token over the url)

**Implementation constraints**

* Should be developed in parallel to current scheduling functionality, to be merged later

**Comment by oliverbarnes** [comment]
@asyp @cromulus admin user receives confirmation (over email for now) the invitee selected a time slot?

**Comment by cromulus** [comment]
yes.

**Comment by oliverbarnes** [comment]
Quick mockups of barebones web interfaces for **Admin user invites a Person to a call** and **Person selects a time slot for call**. Didn't include the email screens as they'll simply be copy with a link.

(they're not visually great, I'm using a free trial of a prototyping tool. and it's been a while since I've used one of these :) )

On the invitation screens, times already taken by confirmed reservations won't appear in the pull downs.

@asyp let me know if I'm missing something. Also, it'd be good to quickly skype again to discuss group scheduling so we understand what likely scenarios we'll cover, and check our current data modeling will be a good starting point for it. @cromulus I'm posting about the data modeling spike on the issue related to it (#23).

## Admin user invites person
![admin user invites person](https://cloud.githubusercontent.com/assets/21290/12760765/27517438-c9cf-11e5-8b99-2c18bf175da3.png)

---

## Admin user invites person (2 time slots)
![admin user invites person 2 time slots](https://cloud.githubusercontent.com/assets/21290/12760764/27193a14-c9cf-11e5-8e46-5c21e2551a7f.png)

---

## Person selects a time slot and makes a reservation
![person selects a time slot](https://cloud.githubusercontent.com/assets/21290/12760766/27518ca2-c9cf-11e5-9d13-43f381c88ce0.png)

**Comment by asyp** [comment]
@oliverbarnes this looks spot on in terms of the functionality we'd want. i think i'd realistically use the third mockup the most.

**Comment by marcoow** [comment]
@asyp: @oliverbarnes and me were also talking about the case where the time slot would be longer than the actual length of the call (e.g. time slot is from 3pm to 5pm but the call length is only 30min). In that case would we allow people to select any starting time for the call that is in that time slot (e.g. start at 3pm or 3:03 or 4:17 or whatever) or should we just let them select in 5minute increments?

That's sth. for the call of course - just posting it here already so it doesn't get lost.

**Comment by asyp** [comment]
I think it makes sense to give set 15 minute increments. These calls really don't last longer than 10min and it's more efficient if I can onboard 4 people in an hour. If it's better for you to test every 30 minutes, that's fine too.

**Comment by oliverbarnes** [comment]
> i think i'd realistically use the third mockup the most.

@asyp actually, the third mockup is what the Person (research subject) sees after you've invited them in the first two mockups :) the first mockup and second are different states of the same invitation interface, and third is where the invitee selects which appointment time they want. I should have elaborated a little further.

By the way, I suggest we switch from calling the user roles User and Person, and use Admin (or Interviewer) and Research Subject instead, which are more descriptive. User and Person are pretty generic IMO.

We can do 15 minute increments, no problem. @marcoow I think set appointment windows are more intuitive for the research subjects, and avoids possible problems where one or two appointments leave no room to others within a time window?

**Comment by asyp** [comment]
@oliverbarnes ah i see! awesome.

**Comment by oliverbarnes** [comment]
I think I have enough to start coding, will get on to it now.

**Comment by oliverbarnes** [comment]
@ganeshbsub let me know if you'd like to pair on it at some point

**Comment by oliverbarnes** [comment]
Updated the user stories and scenarios in the first post, according to the last huddle with Bill and Alexis.

Diff: the invitation will have an event description the admin fills in, and she'll receive a copy of the invite for future reference.

**Comment by marcoow** [comment]
@oliverbarnes: if we decide to base everything on predefined appointment windows we don't really need the abstract time slot model but can just use these predefined timeslots instead (e.g. instead of having that abstract time slot model that says a 10min period between e.g. 3pm and 5pm is needed we could just use 8 time slots between 3pm and 5pm, each 25min long). Each of these time slots would have a capacity then - probably makes everything a lot easier anyway.

```
class Timeslot
  belongs_to :event

  def start; end
  def end; end
  def capacity; end
end

class Event
  has_many :time_slots
end

class Reservation
  belongs_to :time_slot
  belongs_to :person
end
```
