### ISSUE TITLE
Scheduling a call over SMS

### ISSUE THREAD

**Issue by oliverbarnes** [BlueRidgeLabs/kimball#35]
As an admin user
I need to invite a person to a phone call over SMS
If she has that communication preference
At a time fitting my schedule
So I can interview her

As a person (research subject)
With 'SMS' set as the preferred contact method
I want receive and respond to invitations over SMS
Selecting a convenient time slot
So I can participate in a research session

**Scenarios**

Admin user flow the same as [when scheduling over email](https://github.com/BlueRidgeLabs/kimball/issues/24).

Person receives SMS with the event description 
And a numbered list of time slots to select from
She sends an SMS back with the respective number of the selected time slot 
She receives a confirmation SMS her call was booked
Admin receives the same confirmation SMS

Person receives SMS invitation with time options
Declines the invitation by sending an SMS with the number 0
She receives confirmation the invitation was declined
Admin receives notification of the declined invite

Person receives SMS invitation with time options
But responds with something other than the options available, perhaps texting something
She receives an error message offering the options available again

**Further notes**

* Time slots sent out in invitation should be locked for an amount of time to be defined

**Comment by oliverbarnes** [comment]
@cromulus I think you proposed a simplified scenario last project weekly, what was it again? I ended up not updating the issue after the meeting, my bad

**Comment by marcoow** [comment]
@obarnes: first step is to send out the link we're currently sending out via email via sms. Second step is to have candidates reply to the sms to make a reservation instead of using the web ui they reach via the link in the sms.

**Comment by oliverbarnes** [comment]
@marcoow thanks, on it

**Comment by oliverbarnes** [comment]
first simple iteration done, now on to the full fledged version, and let's see how far I get

**Comment by oliverbarnes** [comment]
an unexpected conundrum has come up: how to uniquely identify the event the sms responses from research subjects are responding to, given they can be invited to more than one event? 

The sms invitation doesn't have any metadata where info about the event could be included, so the sms response is dumb about it - it only sends the time slot selection, but it could be from any of the events the subject has been invited to.

One solution could be to send the event id as part of the invitation body, and ask the research subject to include it in the selection - so, say the event id is `109` and the slot picked `3`, she'd send `1093`.

Is this good enough?

**Comment by cromulus** [comment]
Interesting. I like the solution. My thought was that we'd block invitations to new events until the first had "timed out", using a "invitation pending" state, which if ignored, accepted or rejected would then celar and allow for new invitations to be sent.

I like this solution, though. Simple.

part of the problem will be that event IDs will grow relatively large over time. don't want someone to have to type '20345'

Perhaps we place a limit to the number of "events" a person can have open, and then it picks a nubmer between 1-10 that is the indicator of the event and then append the slot id to it?

I'll chat with alexis as well.

**Comment by oliverbarnes** [comment]
Hmm I hadn't connected the dots with the block / time out possibility, yeah that'd ensure a single invitation per person at any given time.

But I agree, id-slot thing is simpler. The id size is an issue for sure, but I'd say we can add it to the backlog, to be tackled after events go into the triple digits? I figure it'll take many months before that happens in any install
