### ISSUE TITLE
Can we use rspec?

### ISSUE THREAD

**Issue by oliverbarnes** [BlueRidgeLabs/kimball#6]
This was pending discussion at the biweekly standup with SmartChicago

**Comment by cromulus** [comment]
discussing now. I'll get back to you momentarily.

**Comment by oliverbarnes** [comment]
all green for rspec? pun intended

**Comment by oliverbarnes** [comment]
@cromulus I'm about to begin on the people registration feature (#5), and will need to have the testing framework defined for that. If no strong feelings against rspec came up, I'm going to go ahead and use it ok?

**Comment by cromulus** [comment]
Yes, lets use rspec.
