### ISSUE TITLE
tire gem (for Elasticsearch) retired

### ISSUE THREAD

**Issue by oliverbarnes** [BlueRidgeLabs/kimball#7]
It was [retired in 2013](https://github.com/karmi/retire/wiki/Tire-Retire) in favor of [elasticsearch-ruby](https://github.com/elasticsearch/elasticsearch-ruby) and [elasticsearch-rails](https://github.com/elastic/elasticsearch-rails).

I think it's a good idea to follow suit and switch to the latter in the people search milestone

**Comment by cromulus** [comment]
Agreed.

**Comment by oliverbarnes** [comment]
:+1: keeping in the backlog and reassigning to me then.

**Comment by cromulus** [comment]
I think the smart chicago team is going to update to a newer version of Tire/Elasticsearch:
https://github.com/smartchicago/kimball/issues/154

**Comment by cromulus** [comment]
With ransack!
